### ISSUE TITLE
Compiler cl can not compile programs

### ISSUE THREAD

**Issue by half2me** [ishmael1985/gstreamer-media-SDK#12]
I followed the instructions, but when I run meson I get the following:
`Compiler cl can not compile programs.`
`A full log can be found at C:\tools\gstreamer-media-SDK\build\meson-logs\meson-log.txt`

The log file says:
``` bash
LINK : fatal error LNK1104: cannot open file 'kernel32.lib'

-----
Sanity check compile stderr:
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.


-----
```

What am I doing wrong?

**Comment by ishmael1985** [comment]
What Visual Studio version are you using? (presumably Visual Studio 2015)
This file (kernel32.lib) would normally be part of the Windows SDK, so make sure you install that.

This might help:
https://stackoverflow.com/questions/15053337/fatal-error-lnk1104-cannot-open-file-kernel32-lib

**Comment by half2me** [comment]
@ishmael1985 it was a problem with my system setup (not quite sure exactly what it was)
I tried building this with Appveyor, see my fork here: https://github.com/half2me/gstreamer-media-SDK
Take a look at my appveyor file, I also made some changes to the meson build file, because:
It doesn't want to recognize msdk, even though I set the environment variable. It also tries to concatinate `/lib/x64` to the MEDIASDKROOT which causes problems on windows :) How do I get this to build?

**Comment by ishmael1985** [comment]
Seems like you're trying to automate the setup all in one go. The MSDK installer has an option to set the INTELMEDIASDKROOT in the wizard, I believe. Normally after you set up the environmental variable, you need to restart the command prompt for the environmental variable changes to take effect.

**Comment by half2me** [comment]
@ishmael1985 I set the INTELMEDIASDKROOT manually to the correct value. It tries to append `/lib/x64` to the end of that... Did the build work for you? Do I have to run in under mingw or something?

**Comment by ishmael1985** [comment]
Of course it worked, without having to resort to MinGW / MSYS2 :) When you try installing manually does it work for you?

**Comment by half2me** [comment]
I can't install manually because my only windows setup keeps giving me the error that I wrote above, so I tried to use AppVeyor, where I finally had success in everything except including the msdk

**Comment by ishmael1985** [comment]
Strange... can you compile the project manually at least?
https://github.com/ishmael1985/gstreamer-media-SDK/tree/windows

**Comment by half2me** [comment]
I'll try. Wow, I only just noticed you had a branch for windows :)

**Comment by half2me** [comment]
@ishmael1985 is there some contact where I can reach you? IRC, chat, skype something?

**Comment by ishmael1985** [comment]
Let's resolve the issue here first. You definitely have setup issues. Does the project compile for you?

**Comment by half2me** [comment]
Okay, any help is much apreciated.
To be honest, I have no experience with visual studio, or even conpiling on windows. I only did work on linux and osx, where I worked with autoconf, make, cmake, etc. I have been using gstreamer for quite awhile on linux and osx, but just recently had the need to have it run on windows. The absence of any hardware acceleration in the default precompiled binaries for win made it necessary to compile something from source. I’ve tried the gst-plugins-bad package, which includes an msdk plugin, but had no success. This project is the only one I found, which mentions windows support.

**Comment by ishmael1985** [comment]
Ok, now you put it that way, my skype id is ishmael.sameen
I can provide you the binaries directly if you request, but it's better to resolve your setup issue for future development work.
Try modifying your Visual Studio setup as below:
<img width="350" alt="vs_setup" src="https://user-images.githubusercontent.com/5097238/32978920-c16aa974-cc4b-11e7-995c-15c5b5aeb165.png">

**Comment by half2me** [comment]
Hi @ishmael1985 I've managed to build it. I just needed to set the environment variables for gstreamer dev location, and after that it was building just fine. However, I would be glad to have your help to get this building on Appveyor as well, so that we can have automatic builds for any updates.

Thank you again for your help. I will add you on skype
