### ISSUE TITLE
loop repeat frames, when using mfxvpp.

### ISSUE THREAD

**Issue by lubagov** [ishmael1985/gstreamer-media-SDK#17]
Hello Ishmael!
I try build, last version from sources, with new version iHD driver and Intel MSDK, with stock ubuntu 16.4.4 kernel (4.13.0-36). 
But now, I get strange result, in my app.
https://drive.google.com/open?id=167ES4MJe2rcJYpg0VrC-2LRVZ5OUKwv2
My pipeline:
```
    jparse = gst_element_factory_make ("jpegparse","jparse");
    jpgdec = gst_element_factory_make ("mfxjpegdec", "jdec");
    gldownload = gst_element_factory_make ("gldownload", "gldownl");
    capsfilter = gst_element_factory_make ("capsfilter", "resfilter");
    vsink = gst_element_factory_make ("appsink", "vsink");

    g_signal_connect( vsink, "new-sample", G_CALLBACK( new_sample_intel ), &gstData);
    g_object_set(G_OBJECT(vsink), "drop", 1, NULL);
    g_object_set(G_OBJECT(vsink), "max-buffers", 1, NULL);
    g_object_set(G_OBJECT(vsink), "emit-signals", 1, NULL);
    g_object_set(G_OBJECT(vsink), "sync", 0, NULL);

    videoConvert = gst_element_factory_make("mfxvpp","vconv");
    g_object_set(G_OBJECT(videoConvert), "brightness", brightness, NULL);
    g_object_set(G_OBJECT(videoConvert), "contrast", contrast, NULL);
    g_object_set(G_OBJECT(videoConvert), "detail", detail, NULL);
    g_object_set(G_OBJECT(videoConvert), "denoise", denoise, NULL);
....
    /* Create the empty pipeline */
    pipeline = gst_pipeline_new ("test-pipeline");
....
    gst_bin_add_many (GST_BIN (pipeline), m_videoSrc, capsfilter, jparse, jpgdec, videoConvert,  gldownload, vsink, NULL);
    gst_element_link_many (m_videoSrc, capsfilter, jparse, jpgdec, videoConvert, gldownload, vsink, NULL);
```
When, i tr to find, after what commit it happens, when i revert commit 835bd68e2b4d286dd52aacdc905853cb4168b282 all fine working. 
What is maybe, what is wrong? Same situation, if i have in pipeline without "gldownload", and have output in sistem memory, but only in my app!

**Comment by ishmael1985** [comment]
You say this works when commit https://github.com/ishmael1985/gstreamer-media-SDK/commit/835bd68e2b4d286dd52aacdc905853cb4168b282 is reverted? I'll restore it back, this is me doing some aggresive cleanups, memory reset seems to be important after all!

**Comment by ishmael1985** [comment]
Can you get the latest source in my development branch and see if it works well for you?

https://github.com/ishmael1985/gstreamer-media-SDK/tree/development

**Comment by lubagov** [comment]
Yes, here, it working well

**Comment by ishmael1985** [comment]
Thanks a lot, I appreciate that you have found the commit that causes your issue. I will merge the revert to my master branch.
Please do close the issue.

**Comment by lubagov** [comment]
Interestingly, this does not happen in gst-launch, only in my code. What is difference, i don't know...
Big thank you, for your work!
