### ISSUE TITLE
No features found when building Windows branch

### ISSUE THREAD

**Issue by gordeaoux** [ishmael1985/gstreamer-media-SDK#19]
Using the windows branch's sln (or building using meson from the master branch) produces gstmfx.dll with no features or symbols. When running "gst-inspect-1.0.exe mfxvpp", there's no plugin for that name, and upping the gst-debug-level to 5 produced these logs from gst-inspect-1.0.exe:

0:00:00.021287485 10796 0000000004144000 DEBUG           GST_REGISTRY gstregistry.c:462:gst_registry_add_plugin:<registry0> adding plugin 000000000414B1E0 for filename "C:\gstreamer\1.0\x86_64\lib\gstreamer-1.0\gstmfx.dll"
0:00:00.021322437 10796 0000000004144000 DEBUG           GST_REGISTRY gstregistrychunks.c:878:_priv_gst_registry_chunks_load_plugin: Added plugin 'mfx' plugin with 0 features from binary registry 

0:00:00.598080131 10796 0000000004144000 DEBUG           GST_REGISTRY gstregistrychunks.c:487:_priv_gst_registry_chunks_save_plugin: Found 0 features in plugin "mfx"

The builds all seem to complete ok (with some linker warnings about missing pdb's). This is using Intel MSDK 2016 r2 or 2017 r1 and gstreamer 1.12.4 and 1.14.0.1 64 bit

**Comment by ishmael1985** [comment]
Could you run Intel Media SDK System Analyzer on your target system and give me the output?

https://software.intel.com/en-us/articles/media-sdk-tools

Also, just to be sure, if you are using the VS2015 solution from the Windows branch, you should build the release version and copy it to your GStreamer system directory.

**Comment by gordeaoux** [comment]
I was just about to respond that my hardware doesn't seem to support it. Apologies! 

It's somewhat hard to tell from the documentation, does this require running on Intel graphics? Or do you just need a chip that supports Intel graphics? For instance, can I have a newer i7 with embedded graphics and run displays off an NVidia GPU?

The following versions of Media SDK API are supported by platform/driver
[opportunistic detection of MSDK API > 1.23]:

        Version Target  Supported       Dec     Enc
        1.0     HW      No
        1.0     SW      Yes             X       X
        1.1     HW      No
        1.1     SW      Yes             X       X
        1.2     HW      No
        1.2     SW      Yes             X       X
        1.3     HW      No
        1.3     SW      Yes             X       X
        1.4     HW      No
        1.4     SW      Yes             X       X
        1.5     HW      No
        1.5     SW      Yes             X       X
        1.6     HW      No
        1.6     SW      Yes             X       X
        1.7     HW      No
        1.7     SW      Yes             X       X
        1.8     HW      No
        1.8     SW      Yes             X       X
        1.9     HW      No
        1.9     SW      Yes             X       X
        1.10    HW      No
        1.10    SW      Yes             X       X
        1.11    HW      No
        1.11    SW      Yes             X       X
        1.12    HW      No
        1.12    SW      Yes             X       X
        1.13    HW      No
        1.13    SW      Yes             X       X
        1.14    HW      No
        1.14    SW      Yes             X       X
        1.15    HW      No
        1.15    SW      Yes             X       X
        1.16    HW      No
        1.16    SW      Yes             X       X
        1.17    HW      No
        1.17    SW      Yes             X       X
        1.18    HW      No
        1.18    SW      Yes             X       X
        1.19    HW      No
        1.19    SW      Yes             X       X
        1.20    HW      No
        1.20    SW      Yes             X       X
        1.21    HW      No
        1.21    SW      Yes             X       X
        1.22    HW      No
        1.22    SW      Yes             X       X
        1.23    HW      No
        1.23    SW      Yes             X       X

Graphics Devices:
        Name                                         Version             State
        NVIDIA Quadro K5000                          23.21.13.9133       Active

System info:
        CPU:    Intel(R) Xeon(R) CPU E5-1630 v3 @ 3.70GHz
        OS:     Microsoft Windows 10 Pro
        Arch:   64-bit

Installed Media SDK packages (be patient...processing takes some time):
        Intel(R) Media Server Studio 2017 R3 - Software Development Kit
        Intel(R) Media SDK 2016 R2

Installed Media SDK DirectShow filters:

Installed Intel Media Foundation Transforms:

**Comment by ishmael1985** [comment]
Your system definitely doesn't have MFX capability, due to lack of an Intel embedded graphics. 

https://ark.intel.com/products/82764/Intel-Xeon-Processor-E5-1630-v3-10M-Cache-3_70-GHz

System Analyzer confirms it, the MFX plugins handled it as they should gracefully.
Regarding your question, as long as you are using Direct3D 11, which is definitely the case since you are on Windows 10, MSDK can run in headless mode, which means as long as the supported Intel graphics driver is present in your system, the MFX plugins will work even if an external graphics such as nVidia or AMD is configured to be the primary display in your system.

**Comment by gordeaoux** [comment]
Awesome - thanks!
