### ISSUE TITLE
mfx gst-libs\mfx\gstmfxdecoder.c:575:gst_mfx_decoder_prepare: Unable to query decode allocation request -3

### ISSUE THREAD

**Issue by hexray-newbee** [ishmael1985/gstreamer-media-SDK#20]
I tested mfxhevcdec on Braswell.
```
gst-launch-1.0 filesrc location=Star.Wars.Episode.IV.A.New.Hope.1977.1080p.Bluray.10bit.265.AAC.51-HazMatt.mkv ! matroskademux ! h265parse ! video/x-h265, profile=main-10 ! mfxhevcdec ! fakesink
```
```
0:00:00.344680933  3796 00000000051B4480 ERROR                    mfx gst-libs\mfx\gstmfxdecoder.c:575:gst_mfx_decoder_prepare: Unable to query decode allocation request -3
ERROR: from element /GstPipeline:pipeline0/GstMatroskaDemux:matroskademux0: Internal data stream error.

** (gst-launch-1.0:3796): CRITICAL **: gst_mfx_surface_new_from_pool: assertion 'pool != NULL' failed
Additional debug info:
matroska-demux.c(5062): gst_matroska_demux_loop (): /GstPipeline:pipeline0/GstMatroskaDemux:matroskademux0:
streaming stopped, reason error (-5)
ERROR: pipeline doesn't want to preroll.
```

**Comment by ishmael1985** [comment]
Thanks. Can you check the HEVC Main 10 decode support using DXVA checker?

http://bluesky23.yukishigure.com/en/DXVAChecker.html

Please show me the screenshot of it like attached.
<img width="469" alt="dxva" src="https://user-images.githubusercontent.com/5097238/38129166-1f1f1590-33fe-11e8-868b-b86314da9ac9.png">

**Comment by hexray-newbee** [comment]
![image](https://user-images.githubusercontent.com/15082228/38129575-31649138-3432-11e8-8181-3975cff90f1a.png)

**Comment by ishmael1985** [comment]
Thanks for the screenshot. So it seems Braswell doesn't support DXVA2 HEVC Main 10 decode in hybrid mode. If it did you'd get something like below:

https://images.anandtech.com/doci/10689/dxva-checker.png
