### ISSUE TITLE
Installation problem on Windows

### ISSUE THREAD

**Issue by niunno** [ishmael1985/gstreamer-media-SDK#22]
Following the "Notes to Windows users" I wanted to try the plugin without compiling it.
I installed gst-mfx-1.14-x86_64 and gstreamer-1.0-devel-x86_64-1.14.1, then I installed gst-mfx-1.14-x86_64.exe .
When I launch the command 
`gst-inspect-1.0 mfxvpp`
the program returns "No such element or plugin 'mfxvpp'".

I repeated the same procedure by using the GStreamer and the gstreamer-media-SDK plugin having version 1.12, but I got the same problem.

I haven't installed all the software requirements because I thought they were necessary only to compile the plugin.

**Comment by niunno** [comment]
As specified by README, the Intel processor generation Coffee Lake is not supported by the plugin, so I could not see the plugin elements.

**Comment by ishmael1985** [comment]
@niunno Coffee Lake should be supported. Also, the installers should be working if you install in the following order (for latest 1.14 and gst-mfx):
* gstreamer-1.0-x86-1.14.4.msi
* gstreamer-1.0-devel-x86-1.14.4.msi
* gst-mfx-1.14-x86_64.exe

Clear your current setup first then follow the order of installation as described.

**Comment by niunno** [comment]
@ishmael1985 I tried to install the plugin by following the order suggested:

( I thought you meant the 64bit version) 
- gstreamer-1.0-x86_64-1.14.4.msi
- gstreamer-1.0-devel-x86_64-1.14.4.msi
- gst-mfx-1.14-x86_64.exe

I also tried the 32bit version:
- gstreamer-1.0-x86-1.14.4.msi
- gstreamer-1.0-devel-x86-1.14.4.msi
- gst-mfx-1.14-x86.exe

I unistalled GStreamer and GStreamer-dev before each installation.

The plugin successfully installs, but when I launch "gst-inspect mfx", the plugin shows 0 features.

**Comment by ishmael1985** [comment]
That is really weird. If you build manually and install, will all plugins be available?

**Comment by niunno** [comment]
Same output, but the ninja invocation reported many warnings. I attach the output.
[out.txt](https://github.com/ishmael1985/gstreamer-media-SDK/files/2456161/out.txt)

**Comment by ishmael1985** [comment]
The build logs look fine, but it's really weird that it doesn't work for Coffee Lake Windows. I don't have a Coffee Lake system though. MSDK sample app such sample_decode.exe and sample_multitranscode, do they work for you?

**Comment by niunno** [comment]
The command
`sample_decode.exe h264 -i ..\content\test_stream.264 -o out1.yuv`
returned 
> [ERROR], sts=MFX_ERR_UNSUPPORTED(-3), CDecodingPipeline::Init, m_mfxSession.Init failed at src\pipeline_decode.cpp:302
> 
> [ERROR], sts=MFX_ERR_UNSUPPORTED(-3), wmain, Pipeline.Init failed at src\sample_decode.cpp:719

`sample_multi_transcode.exe -i::h264 ..\content\test_stream.264 -o::h264 out.h264`
returned
> [ERROR], sts=MFX_ERR_UNSUPPORTED(-3), TranscodingSample::CTranscodingPipeline::Init, m_pmfxSession->InitEx failed at src\pipeline_transcode.cpp:3197
> 
> [ERROR],  sts=MFX_ERR_UNSUPPORTED(-3), TranscodingSample::Launcher::Init, pThreadPipeline->pPipeline->Init failed at src\sample_multi_transcode.cpp:348
>
> [ERROR], sts=MFX_ERR_UNSUPPORTED(-3), wmain, transcode.Init failed at src\sample_multi_transcode.cpp:750

I don't know if I'm doing it right because it seems a configuration problem https://software.intel.com/en-us/node/628520 .

**Comment by ishmael1985** [comment]
@niunno you definitely have a MSDK setup issue if even the reference Intel sample apps have issues running in your system. Try updating the drivers first then try again - https://downloadcenter.intel.com/download/28180/Intel-Graphics-Driver-for-Windows-10?product=80939

**Comment by niunno** [comment]
Unfortunately, the installation wizard returned
> This computer does not meet the minimum requirements for installing the software.

I saw that my processor (i7-8700) is not listed in the valid product list.

I found this driver https://downloadcenter.intel.com/download/27199/Intel-Graphics-Driver-for-Windows-15-47-?product=126686 , but I don't know whether to install it or not because is dated 10/10/2017 .

**Comment by ishmael1985** [comment]
Just go ahead and install the driver you found.

**Comment by niunno** [comment]
The driver I found reported the same problem:
> This computer does not meet the minimum requirements for installing the software.

I'm running a PC with Windows 10 Pro x64.

I saw from https://software.intel.com/en-us/media-sdk that, under "Key Specifications -> Windows", you should have a processor between 3rd and 6th generation. Could it be the cause?

**Comment by ishmael1985** [comment]
@niunno I don't know what to say. You need to report this driver installation bug straight to Intel for your particular hardware. Regarding MSDK, it should be agnostic to the platform, so generations above 6th generation should be supported.

**Comment by niunno** [comment]
Thank you very much for the support. I'll report the bug to Intel.
