### ISSUE TITLE
sudo ninja install step fails

### ISSUE THREAD

**Issue by skyline220** [ishmael1985/gstreamer-media-SDK#24]
Hi,

I am able to get all the way through the installation process fine but I get this error on the last step:

sudo ninja install
log: reading configuration file: install
die: error: unable to read configuration file

Is there anyway to fix?

Thanks

**Comment by skyline220** [comment]
Hi Ishmael,

I was hoping for your help on this, really would like to use this library.

Thanks

**Comment by ishmael1985** [comment]
@skyline220 please provide more details, logs, steps to reproduce, your environment, etc. on this "issue" if you would like anyone to help you out on this if they have the time. Just a message like what you've shown isn't very helpful at all.

**Comment by skyline220** [comment]
Hi @ ishmael1985 ,

I apologize for the lack of information:

Platform: Ubuntu 16.04.04 LTS
Gstreamer version: GStreamer 1.8.3

I cloned the repo and followed the steps in the README.md and was able to configure and build with meson the gst-mfx-build_release.

As the README.md states, I then 

cd ../gst-mfx-build_release/
gst-mfx-build_release$ ninja
[3/3] Linking target gst/mfx/libgstmfx.so.
sudo ninja install
[sudo] password for test: 
log: reading configuration file: install
die: error: unable to read configuration file

That is the error I got and where I am stuck. I do see libgstmfx.so in /gst-mfx-build_release/gst/mfx/

Please let me know any suggestions on how to troubleshoot this error

Thanks

**Comment by ishmael1985** [comment]
Is this a clean install? Doesn't look like to me. Redo every step again.

**Comment by skyline220** [comment]
Hi Ishmael,

Here are the results of the clean installation - I removed the gstreamer-media-SDK and gst-mfx-build folders then:

test@test:~/Downloads/ git clone https://github.com/ishmael1985/gstreamer-media-SDK.git


test@test:~/Downloads/gstreamer-media-SDK$ sudo pip3 install --upgrade meson ninja

The directory '/home/test/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/test/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: meson in /home/orthodevpico/.local/lib/python3.5/site-packages
Requirement already up-to-date: ninja in /home/orthodevpico/.local/lib/python3.5/site-packages
You are using pip version 8.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

test@test:~/Downloads/gstreamer-media-SDK$ export PKG_CONFIG_PATH=/opt/intel/mediasdk/lib/pkgconfig/

test@test:~/Downloads/gstreamer-media-SDK$ ~/Downloads/gstreamer-media-SDK$ meson ../gst-mfx-build_release --prefix=/usr --libdir=lib/x86_64-linux-gnu --buildtype=release
The Meson build system
Version: 0.49.0
Source dir: /home/test/Downloads/gstreamer-media-SDK
Build dir: /home/test/Downloads/gst-mfx-build_release
Build type: native build
Project name: gst_mfx
Project version: 2.1.1
Native C compiler: cc (gcc 5.4.0 "cc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609")
Native C++ compiler: c++ (gcc 5.4.0 "c++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Dependency glib-2.0 found: YES 2.48.2
Dependency gobject-2.0 found: YES 2.48.2
Dependency gio-2.0 found: YES 2.48.2
Dependency gmodule-2.0 found: YES 2.48.2
Dependency gstreamer-1.0 found: YES 1.8.3
Dependency gstreamer-base-1.0 found: YES 1.8.3
Dependency gstreamer-video-1.0 found: YES 1.8.3
Dependency gstreamer-allocators-1.0 found: YES 1.8.3
Dependency gstreamer-pbutils-1.0 found: YES 1.8.3
Dependency mfx found: YES 1.28
Dependency libva found: YES 1.4.0
Dependency libdrm found: YES 2.4.91
Dependency libdrm_intel found: YES 2.4.91
Dependency libva-drm found: YES 1.4.0
Dependency libudev found: YES 229
Library stdc++ found: YES
Library dl found: YES
Dependency gstreamer-gl-1.0 found: YES 1.8.3
Dependency gl found: YES 18.0.5
Dependency egl found: YES 18.0.5
Dependency wayland-client found: YES 1.12.0
Dependency x11 found: YES 1.6.3
Dependency x11-xcb found: YES 1.6.3
Dependency xcb-dri3 found: YES 1.11.1
Dependency xrender found: YES 0.9.9
Dependency xkbcommon found: YES 0.5.0
Dependency xrandr found: YES 1.5.0
Configuring version.h using configuration
Build targets in project: 2
Option buildtype is: release [default: debugoptimized]
Found ninja-1.8.2.git.kitware.dyndep-1.jobserver-1 at /home/orthodevpico/.local/bin/ninja

test@test:~/Downloads/gst-mfx-build_release$ ninja
[37/47] Compiling C object 'gst/mfx/51448e3@@gstmfx@sha/gstmfxvideometa.c.o'.
../gstreamer-media-SDK/gst/mfx/gstmfxpluginbase.c: In function ‘gst_mfx_plugin_base_decide_allocation’:
../gstreamer-media-SDK/gst/mfx/gstmfxpluginbase.c:502:54: warning: passing argument 3 of ‘gst_query_parse_nth_allocation_meta’ from incompatible pointer type [-Wincompatible-pointer-types]
     gst_query_parse_nth_allocation_meta (query, idx, &params);
                                                      ^
In file included from /usr/include/gstreamer-1.0/gst/gstmessage.h:167:0,
                 from /usr/include/gstreamer-1.0/gst/gstevent.h:184,
                 from /usr/include/gstreamer-1.0/gst/gstpadtemplate.h:36,
                 from /usr/include/gstreamer-1.0/gst/gstpad.h:72,
                 from /usr/include/gstreamer-1.0/gst/gstelement.h:57,
                 from /usr/include/gstreamer-1.0/gst/gstbin.h:27,
                 from /usr/include/gstreamer-1.0/gst/gst.h:35,
                 from /usr/include/gstreamer-1.0/gst/base/gstpushsrc.h:27,
                 from ../gstreamer-media-SDK/gst/mfx/gstmfxpluginbase.c:23:
/usr/include/gstreamer-1.0/gst/gstquery.h:425:17: note: expected ‘const GstStructure ** {aka const struct _GstStructure **}’ but argument is of type ‘GstStructure ** {aka struct _GstStructure **}’
 GType           gst_query_parse_nth_allocation_meta  (GstQuery *query, guint index,
                 ^
[47/47] Linking target gst/mfx/libgstmfx.so.

test@test:~/Downloads/gst-mfx-build_release$ sudo ninja install
log: reading configuration file: install
die: error: unable to read configuration file

That is the installation procedure I have, please let me know any suggestions on how to troubleshoot this error.

Thanks

**Comment by ishmael1985** [comment]
As suspected it is your environment. Read your logs and check the ninja executable you're using, i.e. execute 'which ninja'.
I would greatly appreciate it if you would try your best to troubleshoot such issues on your own, rather than trying to waste valuable time of devs who volunteer in open-source projects.
Please close the issue when you're done. Be responsible.
