### ISSUE TITLE
windows branch : what is different from master ?

### ISSUE THREAD

**Issue by boxerab** [ishmael1985/gstreamer-media-SDK#26]
I see you have deleted meson files. Is it not possible to build master with meson,
and backend = vs2017   ?

**Comment by ishmael1985** [comment]
@boxerab this is a pure Visual Studio project which you can use to build 32 and 64-bit version of the plugins.

**Comment by boxerab** [comment]
Thanks. Will I be able to create a VS build from master?

**Comment by ishmael1985** [comment]
@boxerab nope. That is a pure Meson version for building the plugins.

**Comment by boxerab** [comment]
Thanks. Doesn't meson support VS ?

**Comment by ishmael1985** [comment]
Yes it does. But I removed it deliberately from the 'windows' branch in my repo just so it looks cleaner for the purpose it's meant - to directly build the plugins from a Visual Studio project.

**Comment by boxerab** [comment]
Cool. Thanks!
