### ISSUE TITLE
Errors for 32 bit build on VS 2017

### ISSUE THREAD

**Issue by boxerab** [ishmael1985/gstreamer-media-SDK#29]
0 of 714 functions ( 0.0%) were compiled, the rest were copied from previous compilation.
      0 functions were new in current compilation
    Finished generating code
    gstreamer-1.0.lib(ddpqs00425.o) : error LNK2026: module unsafe for SAFESEH image.

**Comment by ishmael1985** [comment]
You should install the GStreamer 32-bit development libraries, done that?

**Comment by boxerab** [comment]
Yes, 32 and 64 bit libraries installed.

**Comment by ishmael1985** [comment]
I googled this error and this has nothing to do with gst-mfx, it's a VS compiler issue. Your best solution is to disable SAFESEH by including  '/SAFESEH:NO'  in the build command line - https://benohead.com/visual-c-module-unsafe-safeseh-image-unable-generate-safeseh-image/

**Comment by boxerab** [comment]
Thanks, this is no longer an issue - didn't have to change anything.
