### ISSUE TITLE
Media SDK 2018 R2 Support

### ISSUE THREAD

**Issue by Bananahavoc** [ishmael1985/gstreamer-media-SDK#30]
Does this repo support Media SDK 2018 R2? Both 2018 R1 and R2 are listed as backwards compatible, but when I use either of those SDKs I get a MFX_WRN_INCOMPATIBLE_VIDEO_PARAM error when preparing the encoder.

**Comment by ishmael1985** [comment]
But it works right? It is a warning after all.

**Comment by Bananahavoc** [comment]
No, on my machine the encoder then errors out in gst_mfx_encoder_prepare because the result of MFXVideoENCODE_Query was MFX_ERR_UNSUPPORTED

**Comment by ishmael1985** [comment]
How about 2018 R1? Mine works with it on Haswell. What's your system configuration?

**Comment by ishmael1985** [comment]
Also please provide me the output of your pipeline.

**Comment by boxerab** [comment]
This works for me on Skylake. @BananaHemic try running `media_sdk_system_analyzer` - my guess is that your hardware is not configured properly.

**Comment by Bananahavoc** [comment]
I rolled back my version of Windows from 1809 to 1803, because the 1809 build caused a number of other issues. Now MSDK 2018 R2 is working on my machine.
