### ISSUE TITLE
[mfxh264enc][Windows][empty file] Problem with mfxh264enc on windows. Pipeline create an empty file. 

### ISSUE THREAD

**Issue by GitBartlomiej** [ishmael1985/gstreamer-media-SDK#35]
I have been using GStreamer recently. I’ve built the following pipeline on Windows:

`gst-launch-1.0 --gst-debug-level=4 videotestsrc num-buffers=100 ! videoparse ! mfxh264enc ! qtmux ! filesink location=myFile.mp4`

I try to encode videotestsrc to h264 format and close video in mp4 container. The mp4 is created but unfortunately it is empty. 

The debugger throw such information:
> 0:00:00.184761824 17868 00000000026740F0 INFO      GST_PLUGIN_LOADING gstplugin.c:901:_priv_gst_plugin_load_file_for_registry: plugin "GStreamer\RunTime\1.0\x86_64\lib\gstreamer-1.0\gstmfx.dll" loaded
> 0:00:00.190209498 17868 00000000026740F0 INFO     GST_ELEMENT_FACTORY gstelementfactory.c:361:gst_element_factory_create: creating element "mfxh264enc"
> 0:00:00.193834941 17868 00000000026740F0 INFO        GST_ELEMENT_PADS gstelement.c:670:gst_element_add_pad:<GstVideoEncoder@00000000032544B0> adding pad 'sink'
> 0:00:00.197040302 17868 00000000026740F0 INFO        GST_ELEMENT_PADS gstelement.c:670:gst_element_add_pad:<GstVideoEncoder@00000000032544B0> adding pad 'src'
> 0:00:00.199848984 17868 00000000026740F0 INFO        GST_ELEMENT_PADS gstelement.c:920:gst_element_get_static_pad: **found pad (null):sink**
> 0:00:00.202281957 17868 00000000026740F0 INFO        GST_ELEMENT_PADS gstelement.c:920:gst_element_get_static_pad: **found pad (null):src**
> 

Full information from debugger here: 
[bad_pipeline_debug_lvl_4.txt](https://github.com/ishmael1985/gstreamer-media-SDK/files/2931128/bad_pipeline_debug_lvl_4.txt)

Gstreamer version which I use: 1.14 x64
gstmfx: gst-mfx-1.14-x86_64  installed from Realese

**mfxdecode and mfxsink work correctly!** 

Below I paste information from the mediasdk_system_analyzer_64
[mediasdk_system_analyzer_64.txt](https://github.com/ishmael1985/gstreamer-media-SDK/files/2931130/mediasdk_system_analyzer_64.txt)

Please help me find what is wrong
Thank you

**Comment by ishmael1985** [comment]
Did you try using matroskamux?

**Comment by GitBartlomiej** [comment]
Correct pipeline is:
`gst-launch-1.0 videotestsrc num-buffers=100 ! videoconvert! mfxh264enc ! qtmux ! filesink location=myFile.mp4 `                                                       

For matroskamux:
`gst-launch-1.0 videotestsrc num-buffers=100 ! videoconvert ! mfxh264enc ! matroskamux ! filesink location=output.mkv   ` 

Does gstreamer-media-SDK support **Intel UHD** Graphics 620 (i7-8550U)? I experience some problems on this processor with those pipelines. In case Intel HD everything works.

**Comment by ishmael1985** [comment]
Cool, I believe you can close this then.

**Comment by GitBartlomiej** [comment]
I am sorry but I have one more question. Does gstreamer-media-SDK support Intel UHD Graphics 620 (i7-8550U)?

**Comment by ishmael1985** [comment]
yes.

**Comment by GitBartlomiej** [comment]
Thanks
