### ISSUE TITLE
Question: how does this plugin differ from msdk plugin currently in gst-plugins-bad ?

### ISSUE THREAD

**Issue by boxerab** [ishmael1985/gstreamer-media-SDK#36]

**Comment by boxerab** [comment]
mdsk plugin gets better performance for my pipeline, but is more unstable, and has image artifacts : green horizontal line at top of image.

**Comment by ishmael1985** [comment]
That's interesting... what's your pipeline and how much faster was it? Theoretically, it should be the same between both.

**Comment by boxerab** [comment]
I haven't really done a careful comparison, but I think the speed difference isn't decoding, but rather how the decoder communicates with video sink. msdk doesn't have its own sink, so it seems to perform better with standard windows sinks such as d3dvideosink or glimagesink.

**Comment by boxerab** [comment]
btw, the green artifact disappeared on reboot, but there is a severe memory leak with msdk, making it unusable until I plug it.

**Comment by boxerab** [comment]
it turns out my performance test wasn't "apples to apples"- turns out this plugin's perf is equal to or better than msdk. Bien Fait !!  Will the windows branch work with Linux ? or is it just windows ? I would like to put this in the GStreamer repo so it will be maintained by more people.

**Comment by ishmael1985** [comment]
Yep it works on both Windows and Linux. We did try to push these plugins to gst-plugin-bad a long time ago, but it seems the maintainers went ahead with their own version.

**Comment by boxerab** [comment]
Nice. I don't see why there shouldn't be two plugins for Media SDK, especially as `msdk` plugin in gst-bad has significant memory leaks, and artifacts.
