### ISSUE TITLE
Stream with Closed Captions

### ISSUE THREAD

**Issue by mort1k** [ishmael1985/gstreamer-media-SDK#39]
How is it possible to filter packets with additional information?

in pipe uridecodebin>mfxvpp>mfxenc get: 
>unused pending closed captions
>mfx gstmfxencoder.c:1198:gst_mfx_encoder_prepare: Incompatible video params detected 5

**Comment by ishmael1985** [comment]
Not  sure what you mean, but the log message you see is a warning  you can safely ignore.
